[package]
name = "lambda-foo"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.5.1"
serde_json = "1.0.81"
tokio = { version = "1", features = ["full"] }
openssl = {version = "0.10.40", features = ["vendored"]}
reqwest = { version = "0.11", features = ["json"] }