[package]
name = "rust-roaring-bitmap-foo"
version = "0.1.0"
authors = ["Ishwor Gurung <me@ishworgurung.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
croaring = "0.4.4"